### ISSUE TITLE
Read timeout when tailing `docker push`

### ISSUE THREAD

**Issue by vsudilov** [adsabs/mission-control#10]
```
[2015-07-29 15:37:54,276: ERROR/Worker-5] UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
Traceback (most recent call last):
  File "/proj.adszee/mission-control/mc/tasks.py", line 82, in build_docker
    builder.run()
  File "/proj.adszee/mission-control/mc/builders.py", line 40, in run
    self.push()
  File "/proj.adszee/mission-control/mc/builders.py", line 148, in push
    for line in status:  # This effectively blocks on `docker push`
  File "/proj.adszee/mission-control/venv/lib/python2.7/site-packages/docker/client.py", line 194, in _stream_helper
    data = reader.read(1)
  File "/proj.adszee/mission-control/venv/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 258, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
[2015-07-29 15:37:54,277: INFO/Worker-5] Build f15bbab8856563f7a9c394a761a43c733baf8cfc status built/pushed True/False
```

**Comment by vsudilov** [comment]
Note that the push is still in progress when this hits the logs: 

```
docker push adsabs/recommender_service:8ccbc2f6fc80cba4137f88fe566ecb96fa0bf7e8
FATA[0000] Error response from daemon: push adsabs/recommender_service is already in progress
```
